CREATE TABLE IF NOT EXISTS drops (
    dropId TEXT PRIMARY KEY,
    created DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    text TEXT NOT NULL,
    hearts INTEGER DEFAULT 0,
    dropId TEXT NOT NULL,
    FOREIGN KEY (dropId) REFERENCES drops(dropId)
);

CREATE TABLE IF NOT EXISTS submissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    text TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    priority INTEGER DEFAULT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP
);