CREATE TABLE IF NOT EXISTS drops (
    dropId TEXT PRIMARY KEY,
    created DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    text TEXT NOT NULL,
    hearts INTEGER DEFAULT 0,
    dropId TEXT NOT NULL,
    FOREIGN KEY (dropId) REFERENCES drops(dropId)
);

CREATE TABLE IF NOT EXISTS submissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    text TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    priority INTEGER DEFAULT NULL,
    sort_order INTEGER DEFAULT NULL,
    ip_address TEXT,
    created DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS email_subscribers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    active INTEGER DEFAULT 1,
    unsubscribe_token TEXT NOT NULL UNIQUE,
    created DATETIME DEFAULT CURRENT_TIMESTAMP
);